name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yourusername/your-app-name:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'  # Or specify a version you need

    - name: Set kubectl context
      run: kubectl config use-context your-context-name

    - name: Deploy to Kubernetes
      run: kubectl set image deployment/boomboompow your-app-name=yourusername/your-app-name:latest
